image:
  repository: autobase/console
  tag: latest
  pullPolicy: IfNotPresent

automationImage: autobase/automation:latest

token: "9d4d2fd7f4dbd7e4d1ef7f3c95d1b6e7d2e7d4b3d8f2b8d4d0a1c2b3d4e5f6a7"

service:
  type: LoadBalancer
  port: 80

persistence:
  enabled: true
  size: 10Gi
  storageClass: microk8s-hostpath

ingress:
  enabled: false
  className: nginx
  host: autobase.local

dockerSocket:
  enabled: true
  hostPath: /var/run/docker.sock

serviceAccount:
  create: true
  name: ""

ingress:

  enabled: false

  className: nginx

  hostname: autobase.local

  tls:

    enabled: false

    secretName: autobase-tls