apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "autobase.fullname" . }}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: {{ include "autobase.fullname" . }}

  template:
    metadata:
      labels:
        app: {{ include "autobase.fullname" . }}

    spec:
      serviceAccountName: {{ include "autobase.serviceAccountName" . }}

      containers:
        - name: console

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 80

          env:
            - name: PG_CONSOLE_DOCKER_IMAGE
              value: {{ .Values.automationImage }}

            - name: PG_CONSOLE_AUTHORIZATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "autobase.fullname" . }}
                  key: AUTH_TOKEN

          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgresql

            - name: ansible
              mountPath: /tmp/ansible

            - name: docker
              mountPath: /var/run/docker.sock

      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: {{ include "autobase.fullname" . }}

        - name: ansible
          emptyDir: {}

        - name: docker
          hostPath:
            path: {{ .Values.dockerSocket.hostPath }}